packages:
  - "apps/*"
  - "packages/*"
  - "infra"

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  aws-cdk: 2.1143.0
  aws-cdk-lib: 2.271.0
  constructs: 10.8.1
  tsx: 4.20.6

catalogMode: strict

engineStrict: false
